config/routes.rb
Outpouring::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :pages
  resources :products
  resources :contacts
  resources :links
  resources :roles
  resources :profiles
  resources :partials

  match "article_partial", :to => "articles#article_partial"

  # blogs
  resources :articles do
    resources :comments
    collection { post :sort }
  end
  match 'articles/:id/article_status', to: 'articles#article_status', as: 'article_status'
  match "articles/:id/article_starts_at", to: "articles#article_starts_at", as: "article_starts_at"
  match "articles/:id/article_ends_at", to: "articles#article_ends_at", as: "article_ends_at"

  # pages
  resources :pages do
    collection { post :sort }
  end
  match 'pages/:id/status', to: 'pages#status', as: 'status'

  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"

  

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :controllers => { :registrations => "users/registrations" }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Piggybak::Engine => '/checkout', :as => 'piggybak'

  match 'dashboard', :to => 'static_pages#dashboard'
  match 'article_index', :to => 'articles#article_index'
  # match "users/:id/update", to: "users#update"

  
  root :to => "pages#show", :id => 'home'


end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :address1, :address2, :company, :email1, :email2, :fax ,:quote, :phone1, :phone2
   
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController 
	before_filter :authenticate_user!, :except => [:show] # devise method
	layout 'dashboard'
	def new 
		@profile = Profile.new	
	end

	def index
		@profiles = Profile.all 
	end

	def show 
		find_profile
	end

	def edit 
		find_profile
	end

	def create 
		@profile = Profile.new(params[:profile])
		respond_to do |format|
			if @profile.save
				format.html { redirect_to @profile, :notice => "The #{@profile.company} profile was successfully created" }
				format.js
			else
				format.html { redirect_to "new", :notice => "profile could not be created. Please fill out all ** fields"}
			end
		end
	end

	def update
		find_profile
		respond_to do |format|
			if @profile.update_attributes(params[:profile])
				format.html { redirect_to @profile, :notice => "The #{@profile.name} profile was succesfully updated"}
				format.js
			else
				format.html { render :action => "edit"}
			end
		end
	end

	def destroy
		find_profile
		@profile.destroy
		respond_to do |format|
			format.html { redirect_to root_url}
			format.js
		end
	end

	def find_profile 
		@profile = Profile.find(params[:id])
	end

end

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
	<%= render 'shared/errors', object: @profile %>
	<div class="field">
		<%= f.label :company %>
		<%= f.text_field :company %>
	</div>
	<div class="field">
		<%= f.label :quote %>
		<%= f.text_field :quote %>
	</div>
	<div class="field">
		<%= f.label :address1 %>
		<%= f.text_field :address1 %>
	</div>
	<div class="field">
		<%= f.label :address2 %>
		<%= f.text_field :address2 %>
	</div>
	<div class="field">
		<%= f.label :phone1 %>
		<%= f.text_field :phone1 %>
	</div>
	<div class="field">
		<%= f.label :phone2 %>
		<%= f.text_field :phone2 %>
	</div>
	<div class="field">
		<%= f.label :email1 %>
		<%= f.text_field :email1 %>
	</div>
	<div class="field">
		<%= f.label :email2 %>
		<%= f.text_field :email2 %>
	</div>
	<div class="field">
		<%= f.label :fax %>
		<%= f.text_field :fax %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

 

app/views/profiles/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
	<h1>Profile</h1> 
	<div class="column_title pages">
		<%= content_tag :p, link_to("+ New", new_profile_path), class: "new_instance_button" %>
		
		
	</div>

	<ul class="model_table">
		<% @profiles.each do |profile| %>
			<li>
				<ul class="instance_detail">
					<% hidden_attributes = %w[id created_at updated_at] %>
					<% profile.attributes.each do |attr_name, attr_value| %>
						<% if attr_value && !hidden_attributes.include?(attr_name) %>
							<%= content_tag :li, attr_name, class: "profile_title" %>
							<%= content_tag :li, attr_value, class: "title" %><br />
						<% end %>
					<% end %>

					<%= render "shared/crud_btns_without_view", object: profile %>
				</ul>
				<br class="clear">
			</li>
		<% end %>
	</ul>

app/views/profiles/new.html.erb
<h1>New</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<ul class="model_table">
	<li>
		<ul class="instance_detail">
			<% hidden_attributes = %w[id created_at updated_at] %>
				<% @profile.attributes.each do |attr_name, attr_value| %>
					<% if attr_value  && !hidden_attributes.include?(attr_name) %>
						<%= content_tag :li, "#{attr_name}: ", class: "profile_title" %>
						<%= content_tag :li, attr_value, class: "title" %><br />
				<% end %>
			<% end %>
			
			<ul class="crud_buttons">
				<%= content_tag :li, link_to("edit", edit_profile_path(@profile)), class:"edit" %>	
				<%= content_tag :li, link_to("delete", profile_path(@profile), :confirm => "are you sure?", :method => :delete ), class:"delete" %>
			</ul>
		</ul>
		<br class="clear">
	</li>
	<br />

	<%= content_tag :li, link_to('View All Profiles', profiles_path) %>
</ul>