config/routes.rb
Outpouring::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :pages
  resources :products
  resources :contacts
  resources :links
  resources :roles
  resources :profiles
  resources :partials

  match "article_partial", :to => "articles#article_partial"

  # blogs
  resources :articles do
    resources :comments
    collection { post :sort }
  end
  match 'articles/:id/article_status', to: 'articles#article_status', as: 'article_status'
  match "articles/:id/article_starts_at", to: "articles#article_starts_at", as: "article_starts_at"
  match "articles/:id/article_ends_at", to: "articles#article_ends_at", as: "article_ends_at"

  # pages
  resources :pages do
    collection { post :sort }
  end
  match 'pages/:id/status', to: 'pages#status', as: 'status'

  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"

  

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :controllers => { :registrations => "users/registrations" }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Piggybak::Engine => '/checkout', :as => 'piggybak'

  match 'dashboard', :to => 'static_pages#dashboard'
  match 'article_index', :to => 'articles#article_index'
  # match "users/:id/update", to: "users#update"

  
  root :to => "pages#show", :id => 'home'


end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name, :description

  has_and_belongs_to_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController 
	before_filter :authenticate_user!, :except => [:show] # devise method
	layout 'dashboard'
	def new 
		@role = Role.new	
	end

	def index
		@roles = Role.all 
	end

	def show 
		find_role
	end

	def edit 
		find_role
	end

	def create 
		@role = Role.new(params[:role])
		respond_to do |format|
			if @role.save
				format.html { redirect_to @role, :notice => "The #{@role.name} role was successfully created" }
				format.js
			else
				format.html { redirect_to "new", :notice => "role could not be created. Please fill out all ** fields"}
			end
		end
	end

	def update
		find_role
		respond_to do |format|
			if @role.update_attributes(params[:role])
				format.html { redirect_to @role, :notice => "The #{@role.name} role was succesfully updated"}
				format.js
			else
				format.html { render :action => "edit"}
			end
		end
	end

	def destroy
		find_role
		@role.destroy
		respond_to do |format|
			format.html { redirect_to root_url}
			format.js
		end
	end

	def find_role 
		@role = Role.find(params[:id])
	end

end

app/views/roles/_form.html.erb
<%= form_for @role do |f| %> 
	<%= render 'shared/errors', object: @role %> 
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>


<% end %>

app/views/roles/index.html.erb
	<h1>Roles</h1> 
	<div class="column_title pages">
		<%= content_tag :p, link_to("+ New", new_role_path), class: "new_instance_button" %>
		<ul>
			<li class="title">Name</li>
		</ul>
		
	</div>

	<ul class="model_table">
		<% @roles.each do |role| %>
			<li>
				<ul class="instance_detail">
					<%= content_tag :li, role.name, class:"name" %>
					
					<%= render "shared/crud_btns", object: role %>
				</ul>
				<br class="clear">
			</li>
		<% end %>
	</ul>

app/views/roles/new.html.erb
<h1>New Page</h1>
<%= render 'form' %>

app/views/roles/show.html.erb
<ul class="model_table">
	<li>
		<ul class="instance_detail">
			<%= content_tag :li, @role.name, class:"name" %><br />
			<%= content_tag :div, raw(@role.description), class: "view_all" %>
			<ul class="crud_buttons">

				<%= content_tag :li, link_to("edit", edit_role_path(@role)), class:"edit" %>
				
				<%= content_tag :li, link_to("delete", role_path(@role), :confirm => "are you sure?", :method => :delete ), class:"delete" %>
			</ul>
		</ul>
		<br class="clear">
	</li>
	<br />

	<%= content_tag :li, link_to('View All Roles', roles_path) %>
</ul>